version: 0.2

phases:
  install:
    commands:
      - cd frontend/auth-app
      - npm install
  build:
    commands:
      - npm run build
  post_build:
    commands:
      - echo "Deploying to S3"
      - aws s3 sync build/ s3://cloud-kinfra-reactappbucket-uvkckmcddrtg --delete
      - echo "Invalidating CloudFront cache"
      - aws cloudfront create-invalidation --distribution-id E2ABS3RG0V1T5B --paths "/*"
artifacts:
  files:
    - '**/*'
  base-directory: frontend/auth-app/build
